# vim:ft=kitty

## name: Grey Field Dark

## license: MIT

## blurb: deep neutral grey - black

#: Scroll

touch_scroll_multiplier 3
touch_momentum_scroll 1

#: Cursor

cursor_shape beam
cursor_beam_thickness 1
cursor_blink_interval 0.5

#: The basic colors

foreground #E5E5E3
background #000000
selection_foreground #FFFFFF
selection_background #30302F
background_opacity 0.75

#: Cursor colors

cursor #9A9996
cursor_text_color #E5E5E3

#: URL underline color when hovering with mouse

url_color #9A9996

#: kitty window border colors and terminal bell colors

active_border_color #9A9996
inactive_border_color #30302F
bell_border_color #9A9996
visual_bell_color none

#: OS Window titlebar colors

wayland_titlebar_color #151515
macos_titlebar_color #151515

#: Tab bar colors

active_tab_foreground #000000
active_tab_background #9A9996
inactive_tab_foreground #858583
inactive_tab_background #151515
tab_bar_background #080808
tab_bar_margin_color none

#: Colors for marks

mark1_foreground #101010
mark1_background #9A9996
mark2_foreground #101010
mark2_background #9A9996
mark3_foreground #101010
mark3_background #9A9996

#: The basic 16 colors

#: black

color0 #6E6E6C
color8 #5C5C59

#: red

color1 #858583
color9 #B5B4B1

#: green

color2 #858583
color10 #B5B4B1

#: yellow

color3 #9A9996
color11 #C2C1BE

#: blue

color4 #858583
color12 #B5B4B1

#: magenta

color5 #858583
color13 #B5B4B1

#: cyan

color6 #9A9996
color14 #C2C1BE

#: white

color7 #E5E5E3
color15 #FFFFFF