# vim:ft=kitty

## name: Osaka Jade
## license: MIT
## blurb: Osaka Jade — Noctalia Community Theme

#: Scroll

touch_scroll_multiplier 3
touch_momentum_scroll 1

#: Cursor

cursor_shape beam
cursor_beam_thickness 1
cursor_blink_interval 0.5

#: The basic colors

foreground #DADADA
background #141B1E
selection_foreground #DADADA
selection_background #141B1E
background_opacity 0.5

#: Cursor colors

cursor #DADADA
cursor_text_color #141B1E

#: URL underline color when hovering with mouse

url_color #1E9177

#: kitty window border colors and terminal bell colors

active_border_color #1E9177
inactive_border_color #0F251F
bell_border_color #1E9177
visual_bell_color none

#: OS Window titlebar colors

wayland_titlebar_color #081512
macos_titlebar_color #081512

#: Tab bar colors

active_tab_foreground #141B1E
active_tab_background #1E9177
inactive_tab_foreground #99A8A4
inactive_tab_background #0F251F
tab_bar_background #081512
tab_bar_margin_color none

#: Colors for marks

mark1_foreground #141B1E
mark1_background #1E9177
mark2_foreground #141B1E
mark2_background #1E9177
mark3_foreground #141B1E
mark3_background #1E9177

#: The basic 16 colors

#: black

color0 #232A2D
color8 #464E50

#: red

color1 #D96C6C
color9 #E57A7A

#: green

color2 #8CBF75
color10 #9DCE83

#: yellow / olive

color3 #C8B86A
color11 #D8C878

#: olive

color4 #A5A85F
color12 #B8B96B

#: muted rose

color5 #B47A88
color13 #C48796

#: jade / teal

color6 #5FAF9A
color14 #6BC4AA

#: white

color7 #B3B9B8
color15 #BDC3C2