-- Generated by HyprMod

-- Settings
hl.config({
    general = {
        gaps_in = 12,
        layout = "dwindle",
        snap = {
            enabled = true,
        },
    },
    misc = {
        animate_manual_resizes = false,
        animate_mouse_windowdragging = false,
        disable_splash_rendering = true,
    },
})
