# vim:ft=kitty

## name: Emerald Field Dark

## license: MIT

## blurb: pure emerald green - black

#: Scroll

touch_scroll_multiplier 3
touch_momentum_scroll 1

#: Cursor

cursor_shape beam
cursor_beam_thickness 1
cursor_blink_interval 0.5

#: The basic colors

foreground #F2F7F4
background #000000
selection_foreground #FFFFFF
selection_background #163A29
background_opacity 0.6

#: Cursor colors

cursor #2EC27E
cursor_text_color #07110C

#: URL underline color when hovering with mouse

url_color #2EC27E

#: kitty window border colors and terminal bell colors

active_border_color #2EC27E
inactive_border_color #163A29
bell_border_color #239A63
visual_bell_color none

#: OS Window titlebar colors

wayland_titlebar_color #0D1F16
macos_titlebar_color #0D1F16

#: Tab bar colors

active_tab_foreground #FFFFFF
active_tab_background #163A29
inactive_tab_foreground #82968B
inactive_tab_background #0D1F16
tab_bar_background #080F0B
tab_bar_margin_color none

#: Colors for marks

mark1_foreground #07110C
mark1_background #2EC27E
mark2_foreground #07110C
mark2_background #5A7565
mark3_foreground #07110C
mark3_background #45D992

#: The basic 16 colors

#: black
color0 #0D1711
color8 #4D6657

#: red
color1 #D95757
color9 #F27777

#: green
color2 #2EC27E
color10 #58E69A

#: yellow
color3 #B9D96A
color11 #D8EF86

#: blue
color4 #269A62
color12 #45C982

#: magenta
color5 #A87991
color13 #C995AE

#: cyan
color6 #2EAA6D
color14 #5BE39A

#: white
color7 #F2F7F4
color15 #FFFFFF