background = 0xE60F0F10
base = 0xE6151518
alternate_base = 0xE61B1B1E


text = 0xFFF2F2F2
bright_text = 0xFFF5F5F5


accent = 0xFF9A9996
accent_secondary = 0xFF9A9996


searchbar_background = 0xE6151518
searchbar_border = 0x40262629
searchbar_focus = 0xFF9A9996