wallpaper {
    monitor = DP-2
    path = /home/hypr/Pictures/Wallpapers/room2.jpg
    fit_mode = fill
}

wallpaper {
    monitor = HDMI-A-2
    path = /home/hypr/Pictures/Wallpapers/room2.jpg
    fit_mode = fill
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/hypr/Pictures/Wallpapers/room2.jpg
    fit_mode = fill
}


splash=false
