background {
    monitor =
    path = /home/hypr/Pictures/Wallpapers/room2.jpg

    blur_passes = 3
    blur_size = 3
}

input-field {
    monitor =
    size = 85, 35
    outline_thickness = 1

    dots_size = 0.20
    dots_spacing = 0.8

    outer_color = rgba(21, 21, 24, 0.0)
    inner_color = rgba(15, 15, 16, 0.0)

    font_color = rgb(154, 153, 150)

    position = 0, -15
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%I:%M")"

    color = rgb(154, 153, 150)

    font_size = 36
    font_family = JetBrainsMono Nerd Font
    
    position = 0, 25
    halign = center
    valign = center
}
