# vim:ft=kitty

## name: Grey Field Dark

## license: MIT

## blurb: deep neutral grey - black

#: Scroll

touch_scroll_multiplier 3
touch_momentum_scroll 1

#: Cursor

cursor_shape beam
cursor_beam_thickness 1
cursor_blink_interval 0.5

#: The basic colors

foreground #F2F1E8
background #000000
selection_foreground #FFFFFF
selection_background #353535
background_opacity 0.6

#: Cursor colors

cursor #8D8414
cursor_text_color #F2F1E8

#: URL underline color when hovering with mouse

url_color #8D8414

#: kitty window border colors and terminal bell colors

active_border_color #8D8414
inactive_border_color #353535
bell_border_color #8D8414
visual_bell_color none

#: OS Window titlebar colors

wayland_titlebar_color #171717
macos_titlebar_color #171717

#: Tab bar colors

active_tab_foreground #FFFFFF
active_tab_background #353535
inactive_tab_foreground #8F8D87
inactive_tab_background #171717
tab_bar_background #0A0A0A
tab_bar_margin_color none

#: Colors for marks

mark1_foreground #0A0A0A
mark1_background #8D8414
mark2_foreground #0A0A0A
mark2_background #8D8414
mark3_foreground #0A0A0A
mark3_background #8D8414

#: The basic 16 colors

#: black

color0 #2A2A28
color8 #66645F

#: red

color1 #8D8414
color9 #B1AA5A

#: green

color2 #8D8414
color10 #B1AA5A

#: yellow

color3 #8D8414
color11 #B1AA5A

#: blue

color4 #8D8414
color12 #B1AA5A

#: magenta

color5 #8D8414
color13 #B1AA5A

#: cyan

color6 #8D8414
color14 #B1AA5A

#: white

color7 #A6A39A
color15 #F2F1E8