# vim:ft=kitty

## name: Olive Field Dark

## license: MIT

## blurb: deep olive gold - black

#: Scroll

touch_scroll_multiplier 3
touch_momentum_scroll 1

#: Cursor

cursor_shape beam
cursor_beam_thickness 1
cursor_blink_interval 0.5

#: The basic colors

foreground #F2F1E8
background #000000
selection_foreground #FFFFFF
selection_background #353208
background_opacity 0.6

#: Cursor colors

cursor #8D8414
cursor_text_color #0A0A05

#: URL underline color when hovering with mouse

url_color #B5AB28

#: kitty window border colors and terminal bell colors

active_border_color #8D8414
inactive_border_color #353208
bell_border_color #6F6810
visual_bell_color none

#: OS Window titlebar colors

wayland_titlebar_color #171605
macos_titlebar_color #171605

#: Tab bar colors

active_tab_foreground #FFFFFF
active_tab_background #353208
inactive_tab_foreground #8F8D7A
inactive_tab_background #171605
tab_bar_background #0A0A06
tab_bar_margin_color none

#: Colors for marks

mark1_foreground #0A0A05
mark1_background #8D8414
mark2_foreground #0A0A05
mark2_background #696316
mark3_foreground #0A0A05
mark3_background #B5AB28

#: The basic 16 colors

#: black

color0 #111108
color8 #4B4A32

#: red

color1 #B84A42
color9 #E06A60

#: green

color2 #8D8414
color10 #B5AB28

#: yellow

color3 #A99D35
color11 #D0C45A

#: blue

color4 #68703A
color12 #8B9552

#: magenta

color5 #82704A
color13 #A99562

#: cyan

color6 #70754A
color14 #9AA06A

#: white

color7 #F2F1E8
color15 #FFFFFF