# Wayle configuration file
[[modules.custom]]
id = "net"
interval-ms = 10000
command = "ip route get 1.1.1.1 | grep -q 'dev' && echo '󰈀 Connected' || echo '󰌙 Disconnected'"


[[modules.custom]]
id = "clipboard"
command = "cliphist list | wc -l"
interval-ms = 2000
icon-name = "edit-paste-symbolic"
format = "{{ output }}"
