wallpaper {
    monitor = eDP-2
    path = /home/hypr/Pictures/Wallpapers/wallhaven-lm638p_3440x1440.png
    fit_mode = fill
}

wallpaper {
    monitor = eDP-1
    path = /home/hypr/Pictures/Wallpapers/wallhaven-lm638p_3440x1440.png
    fit_mode = fill
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/hypr/Pictures/Wallpapers/wallhaven-lm638p_3440x1440.png
    fit_mode = fill
}


splash=false
