wallpaper {
    monitor = eDP-2
    path = /home/hypr/Pictures/Wallpapers/fantasy-woods.jpg
    fit_mode = fill
}

wallpaper {
    monitor = eDP-1
    path = /home/hypr/Pictures/Wallpapers/fantasy-woods.jpg
    fit_mode = fill
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/hypr/Pictures/Wallpapers/fantasy-woods.jpg
    fit_mode = fill
}


splash=false
