background = 0xFF0F0F10
base = 0xFF151518
alternate_base = 0xFF1B1B1E

text = 0xFFE6E6E6
bright_text = 0xFFF5F5F5

accent = 0xFF8D8414
accent_secondary = 0xFF8D8414

searchbar_background = 0xFF151518
searchbar_border = 0xFF262629
searchbar_focus = 0xFF8D8414