# vim:ft=kitty

## name: Osaka Jade
## license: MIT
## blurb: Osaka Jade — Noctalia Community Theme

#: Scroll

touch_scroll_multiplier 3
touch_momentum_scroll 1

#: Cursor

cursor_shape beam
cursor_beam_thickness 1
cursor_blink_interval 0.5

#: The basic colors

foreground #DADADA
background #0d0d0d
selection_foreground #DADADA
selection_background #1B2825
background_opacity 0.70

#: Cursor colors

cursor #8FC7A8
cursor_text_color #141B1E

#: URL underline color when hovering with mouse

url_color #3FA982

#: kitty window border colors and terminal bell colors

active_border_color #3FA982
inactive_border_color #16352C
bell_border_color #3FA982
visual_bell_color none

#: OS Window titlebar colors

wayland_titlebar_color #081512
macos_titlebar_color #081512

#: Tab bar colors

active_tab_foreground #141B1E
active_tab_background #3FA982
inactive_tab_foreground #91A59D
inactive_tab_background #102820
tab_bar_background #081512
tab_bar_margin_color none

#: Colors for marks

mark1_foreground #141B1E
mark1_background #3FA982
mark2_foreground #141B1E
mark2_background #3FA982
mark3_foreground #141B1E
mark3_background #3FA982

#: The basic 16 colors

#: black

color0 #202A27
color8 #465550

#: red

color1 #D66F6F
color9 #E78383

#: green

color2 #82B878
color10 #9BCB8B

#: yellow / olive

color3 #C5B968
color11 #D9CC79

#: olive green

color4 #789F67
color12 #8FB879

#: muted rose

color5 #B47782
color13 #C48792

#: jade / teal

color6 #58A88D
color14 #6BC3A5

#: white

color7 #B3B9B8
color15 #D0D5D3