background = 0xE6081512

base = 0xE60F251F

alternate_base = 0xE61B6352

text = 0xFFDADADA

bright_text = 0xFFBDC3C2

accent = 0xFF1E9177

accent_secondary = 0xFF26A589

searchbar_background = 0xE60F251F

searchbar_border = 0x401B6352

searchbar_focus = 0x661E9177
